# Generated by Django 5.0.3 on 2024-06-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=2),
            preserve_default=False,
        ),
    ]
