# Generated by Django 5.0.3 on 2024-06-25 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortener', '0002_url_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now),
        ),
    ]
